import { NOMBRE_SECCION } from "../../lib/(ENTITIES_ENUMS)/extenseForm/enum";

const AreaTrabajoPreguntasArray = [
  {
    pregunta: "1. Le gustaría que sus hijos trabajaran en lo mismo que usted:",
    preguntaInputName: "actividadLaboral1",
    opciones: [{ valor: "Si" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta: "2. Le da satisfacción la realización de sus actividades:",
    preguntaInputName: "actividadLaboral2",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta: "3. Está interesado en su trabajo:",
    preguntaInputName: "actividadLaboral3",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta:
      "4. Su trabajo le permite desarrollar sus habilidades y destrezas:",
    preguntaInputName: "actividadLaboral4",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta:
      "5. Su trabajo le permite desarrollar su creatividad e iniciativa:",
    preguntaInputName: "actividadLaboral5",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta:
      "6. Su trabajo le permite el aprendizaje de nuevos conocimientos:",
    preguntaInputName: "actividadLaboral6",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta: "7. Puede usted decidir sobre cómo realizar su trabajo:",
    preguntaInputName: "actividadLaboral7",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta: "8. Puede usted fijar el ritmo de trabajo:",
    preguntaInputName: "actividadLaboral8",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta:
      "9. Sus compañeros son solidarios con usted y valoran su trabajo:",
    preguntaInputName: "actividadLaboral9",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta: "10. Su trabajo es importante para sus jefes:",
    preguntaInputName: "actividadLaboral10",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta:
      "11. Faltó al trabajo en los últimos 12 meses (si la respuesta es 'No', pase al siguiente apartado):",
    preguntaInputName: "actividadLaboral11",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta:
      "12. En cuántas ocasiones distintas faltó al trabajo en los últimos 12 meses (independientemente de cuántos días hayan sido en cada ocasión):",
    preguntaInputName: "actividadLaboral12",
    opciones: [
      { valor: "0 veces" },
      { valor: "1 vez" },
      { valor: "2-3 veces" },
      { valor: "4-5 veces" },
      { valor: "5 o mas veces" },
    ],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta: "13. En cuántas de esas ocasiones fue por motivo de salud:",
    preguntaInputName: "actividadLaboral13",
    opciones: [
      { valor: "0 veces" },
      { valor: "1 vez" },
      { valor: "2-3 veces" },
      { valor: "4-5 veces" },
      { valor: "5 o mas veces" },
    ],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
  {
    pregunta: "14. Cuántos días del año en total faltó por motivos de salud:",
    preguntaInputName: "actividadLaboral14",
    opciones: [
      { valor: "0 veces" },
      { valor: "1 vez" },
      { valor: "2-3 veces" },
      { valor: "4-5 veces" },
      { valor: "5 o mas veces" },
    ],
    tipoPregunta: "positivo",
    sectionKey: "section2",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "satisfaccionLaboral",
  },
];

export default AreaTrabajoPreguntasArray;
