import { NOMBRE_SECCION } from "../../lib/(ENTITIES_ENUMS)/extenseForm/enum";

const FactoresAmbientalesPreguntasArray = [
  {
    pregunta: (
      <>
        En su área de trabajo se encuentra expuesto a:
        <br />
        <br />
        1. Calor
      </>
    ),
    preguntaInputName: "ambientales1",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "2. Frío",
    preguntaInputName: "ambientales2",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "3. Cambios bruscos de temperatura",
    preguntaInputName: "ambientales3",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "4.Falta de ventilación",
    preguntaInputName: "ambientales4",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "5. Humedad",
    preguntaInputName: "ambientales5",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "6. Poca iluminación ",
    preguntaInputName: "ambientales6",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "7. Mucha iluminación",
    preguntaInputName: "ambientales7",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "8. Ruido ",
    preguntaInputName: "ambientales8",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "9. Vibraciones",
    preguntaInputName: "ambientales9",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "10. Radiaciones de soldar",
    preguntaInputName: "ambientales10",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "11. Rayos X",
    preguntaInputName: "ambientales11",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: (
      <>
        En su área de trabajo está usted defaultantemente en contacto con:
        <br />
        <br />
        12. Contaminantes biológicos infecciosos (virus, bacterias,hongos)
      </>
    ),
    preguntaInputName: "ambientales12",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "13. Animales ponzoñosos (víboras, alacranes, abejas) ",
    preguntaInputName: "ambientales13",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "14. Palomas u otras aves ",
    preguntaInputName: "ambientales14",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "16. Humos",
    preguntaInputName: "ambientales15",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "17. Gases o vapores",
    preguntaInputName: "ambientales16",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "18. Líquidos (disolventes o ácidos",
    preguntaInputName: "ambientales17",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: (
      <>
        En su puesto de trabajo tiene condiciones muy peligrosas debidoa:
        <br />
        <br />
        19. Los pisos, techos, paredes, rampas o escaleras
      </>
    ),
    preguntaInputName: "ambientales18",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "20. La falta de guardas, protecciones o dispositivos, de paro de emergencia en las máquinas",
    preguntaInputName: "ambientales19",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "21. Las herramientas que utiliza (de mano, eléctricas o neumáticas)",
    preguntaInputName: "ambientales20",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "22. Las instalaciones (eléctricas, neumáticas o de gas)",
    preguntaInputName: "ambientales21",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "23. La operación, mantenimiento o limpieza de las máquinas o equipos",
    preguntaInputName: "ambientales22",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "24. El manejo, transporte y almacenamiento de materiales y sustancias peligrosas",
    preguntaInputName: "ambientales23",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "25. Los equipos de soldadura y corte",
    preguntaInputName: "ambientales24",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "26. Las compresoras o calderas en el área de labores",
    preguntaInputName: "ambientales25",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "27. La falta de equipos o personal para la prevención, protección o combate contra incendios",
    preguntaInputName: "ambientales26",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "28. La falta de orden o limpieza",
    preguntaInputName: "ambientales27",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "29. La falta de equipo de protección personal o el deficiente mantenimiento. ",
    preguntaInputName: "ambientales28",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: (
      <>
        En su trabajo tiene condiciones insalubres o falta de higiene en:
        <br />
        <br />
        30. Las instalaciones sanitarias (baños, regaderas o vestidores)
      </>
    ),
    preguntaInputName: "ambientales29",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "31. En el comedor y los alimentos ",
    preguntaInputName: "ambientales30",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "32. El agua para beber ",
    preguntaInputName: "ambientales31",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: (
      <>
        Su puesto de trabajo lo obliga a:
        <br />
        <br />
        33. Jornada semanal mayor de 48 hrs.
      </>
    ),
    preguntaInputName: "ambientales32",
    opciones: [{ valor: "si" }, { valor: "no" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "34. Realizar trabajos pendientes en horas o días de descanso o vacaciones",
    preguntaInputName: "ambientales33",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "35. Rotación de turnos",
    preguntaInputName: "ambientales34",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "36. Trabajando nocturno",
    preguntaInputName: "ambientales35",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "37. No poder desatender su tarea por más de 5 minutos",
    preguntaInputName: "ambientales36",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "38. Mucha concentración para no accidentarse",
    preguntaInputName: "ambientales37",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "39. Realizar una tarea muy minuciosa",
    preguntaInputName: "ambientales38",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "40. Un trabajo repetitivo. Si NO, pase a la pregunta 43",
    preguntaInputName: "ambientales39",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "41. El conjunto de tareas que realiza se repite por lo menos cada medio minuto",
    preguntaInputName: "ambientales40",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "42. El conjunto de tareas que realiza se repite por lo menos entre medio minuto y 5 minutos",
    preguntaInputName: "ambientales41",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "43. Cubrir una cuota de producción",
    preguntaInputName: "ambientales42",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "44. Realizar un trabajo a destajo",
    preguntaInputName: "ambientales43",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "45. Soportar una supervisión estricta",
    preguntaInputName: "ambientales44",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "46. Un estricto control de calidad",
    preguntaInputName: "ambientales45",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "47. Estar en comunicación con sus compañeros",
    preguntaInputName: "ambientales46",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "48. Trabajar en un espacio reducido",
    preguntaInputName: "ambientales47",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "49. Estar fijo en su lugar de trabajo",
    preguntaInputName: "ambientales48",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "50. Realizar un trabajo aburrido",
    preguntaInputName: "ambientales49",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "51. Ejecutar un trabajo peligroso",
    preguntaInputName: "ambientales50",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "52. Ejecutar un trabajo denigrante",
    preguntaInputName: "ambientales51",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "53. Recibir órdenes confusas y muy pocas claras de su jefe",
    preguntaInputName: "ambientales52",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "54. Realizar algún trabajo que le puede ocasionar daño a su salud",
    preguntaInputName: "ambientales53",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "55. Realizar esfuerzo físico muy pesado",
    preguntaInputName: "ambientales54",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "1. En su área de trabajo existe algún método o sistema para recibir atención médica o primeros auxilios en caso de ser necesario. ",
    preguntaInputName: "ambientales55",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta:
      "2. Conoce algún programa de salud que se aplique en su empresa. Si No, pase al siguiente apartado. ",
    preguntaInputName: "ambientales56",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
  {
    pregunta: "3. Participa en alguno de ellos",
    preguntaInputName: "ambientales57",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section12",
    sectionId: "factores_ambientales",
    enum_matcher_Attr: "calidadDelAmbienteLaboral",
  },
];

export default FactoresAmbientalesPreguntasArray;
