import { NOMBRE_SECCION } from "../../lib/(ENTITIES_ENUMS)/extenseForm/enum";

const EstadoSisSaludPreguntasArray = [
  {
    pregunta: "1. ¿Le zumban los oídos?",
    preguntaInputName: "situacionsalud1",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "2. ¿Durante el último año ha notado que oye menos?",
    preguntaInputName: "situacionsalud2",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "3. ¿Tiene dificultad para oír a sus compañeros de trabajo a más de un metro de distancia aunque no haya mucho ruido?",
    preguntaInputName: "situacionsalud3",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "4. ¿Con frecuencia ha tenido molestias a la luz normal durante varios días?",
    preguntaInputName: "situacionsalud4",
    opciones: [
      { valor: "Diariamente" },
      { valor: "Alguna vez a la semana" },
      { valor: "Alguna vez al mes" },
      { valor: "Nunca" },
    ],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "5. ¿Con qué frecuencia se le irritan los ojos durante varios días?",
    preguntaInputName: "situacionsalud5",
    opciones: [
      { valor: "Diariamente" },
      { valor: "Alguna vez a la semana" },
      { valor: "Alguna vez al mes" },
      { valor: "Nunca" },
    ],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "6. ¿Le han llorado los ojos o ha tenido comienzo o ardor en varias ocasiones?",
    preguntaInputName: "situacionsalud6",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "7. ¿Sin tener basura, frecuentemente ha tenido sensación de basura en los ojos en varias ocasiones?",
    preguntaInputName: "situacionsalud7",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "8. ¿Ha tenido lagañas defaultantes o supuración en los ojos?",
    preguntaInputName: "situacionsalud8",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "9. ¿Durante el último año tuvo anginas con fiebre alta más de dos veces?",
    preguntaInputName: "situacionsalud9",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "10. ¿Durante el último año ha tenido más de cuatro catarros?",
    preguntaInputName: "situacionsalud10",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "11. ¿Ha tenido escurrimiento o secreción de la nariz de mal olor y color verdoso?",
    preguntaInputName: "situacionsalud11",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "12. ¿Ha tenido congestión y/o dolor a los lados de la nariz o en la frente?",
    preguntaInputName: "situacionsalud12",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "13. ¿Estas molestias han durado más de 15 días?",
    preguntaInputName: "situacionsalud13",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "14. ¿Ha tenido tos en el último año? Si No, pase a la pregunta 17.",
    preguntaInputName: "situacionsalud14",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "15. En este caso tosió con flemas.",
    preguntaInputName: "situacionsalud15",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "16. Usted ha tosido tres meses o más seguidos o más en el último año.",
    preguntaInputName: "situacionsalud16",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "17. Se le reseca la piel frecuentemente.",
    preguntaInputName: "situacionsalud17",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "18. Tiene ardor o comezón en la piel.",
    preguntaInputName: "situacionsalud18",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "19. Le salen ampollas en alguna parte de su cuerpo.",
    preguntaInputName: "situacionsalud19",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "20. Tiene piel con escamas en alguna parte de su cuerpo.",
    preguntaInputName: "situacionsalud20",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "21. Le han salido frecuentemente granos con agua o pus o ronchas.",
    preguntaInputName: "situacionsalud21",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "22. ¿Se le agrita parte de la piel?",
    preguntaInputName: "situacionsalud22",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "23. ¿Ha sufrido algún accidente de trabajo durante el último año?",
    preguntaInputName: "situacionsalud23",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "24. ¿Ha sufrido algún accidente en trayecto durante el último año?",
    preguntaInputName: "situacionsalud24",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "25. Frecuentemente tiene dificultad para conciliar el sueño",
    preguntaInputName: "situacionsalud25",
    opciones: [{ valor: "Siempre" }, { valor: "A veces" }, { valor: "Nunca" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "26. Con frecuencia tiene sueño intranquilo",
    preguntaInputName: "situacionsalud26",
    opciones: [{ valor: "Siempre" }, { valor: "A veces" }, { valor: "Nunca" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "27. Se despierta pocas horas después de haberse dormido y ya no se puede volver a dormir",
    preguntaInputName: "situacionsalud27",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "28. ¿Ha tenido dolor de cabeza más de dos veces por mes?",
    preguntaInputName: "situacionsalud28",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "29. ¿El dolor de cabeza se presenta cuando está nervioso o irritable?",
    preguntaInputName: "situacionsalud29",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "30. ¿El dolor de cabeza es tan fuerte que le impide trabajar?",
    preguntaInputName: "situacionsalud30",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "31. ¿Está acompañado de náusea o vómito, mareo o visión borrosa?",
    preguntaInputName: "situacionsalud31",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "32. ¿Antes de que aparezca el dolor tiene sensaciones que le avisan que va a aparecer?",
    preguntaInputName: "situacionsalud32",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "33. ¿El dolor se presenta solo en un lado de la cabeza?",
    preguntaInputName: "situacionsalud33",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "Indique si ha padecido alguna lesión en las partes del cuerpo mencionadas debajo (último año)",
    preguntaInputName: "Indique si ha padecido alguna lesión",
    // placeholder: "parte del cuerpo",
    // opciones: [],
  },
  {
    pregunta: "34. Cuello:",
    preguntaInputName: "situacionsalud35",
    opciones: [{ valor: "Sin molestias" }, { valor: "Con molestias" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "35. Hombro, codos, muñecas o manos:",
    preguntaInputName: "situacionsalud36",
    opciones: [{ valor: "Sin molestias" }, { valor: "Con molestias" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "36. Espalda, cintura, cadera o asentaderas:",
    preguntaInputName: "situacionsalud37",
    opciones: [{ valor: "Sin molestias" }, { valor: "Con molestias" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "37. Muslos, rodillas, tobillos o pies:",
    preguntaInputName: "situacionsalud38",
    opciones: [{ valor: "Sin molestias" }, { valor: "Con molestias" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "38. ¿Ha tenido mucho dolor en la parte baja de la espalda?",
    preguntaInputName: "situacionsalud39",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "39. ¿En caso afirmativo el dolor se corre a la pierna?",
    preguntaInputName: "situacionsalud40",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "40. ¿Ha tenido varices en las piernas?",
    preguntaInputName: "situacionsalud41",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "41. ¿Durante el último año ha tenido hemorroides?",
    preguntaInputName: "situacionsalud42",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta:
      "42. Durante el último año le ha diagnosticado un medico alguna enfermedad: ",
    preguntaInputName: "situacionsalud43",
    opciones: [{ valor: "Sí" }, { valor: "No" }],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
  {
    pregunta: "¿Cuál?:",
    preguntaInputName: "situacionsalud44",
    opciones: [],
    tipoPregunta: "positivo",
    sectionKey: "section5",
    sectionId: "salud_general",
    enum_matcher_Attr: "estadoDeSalud",
  },
];

export default EstadoSisSaludPreguntasArray;
