export const FactoresSocioEcoPreguntasArray = [
  {
    pregunta: "1. Área o departamento donde trabaja:  ",
    preguntaInputName: "socioeconomico1",
    opciones: [
      { valor: "Administración" },
      { valor: "Recursos Humanos" },
      { valor: "Ventas" },
      { valor: "Marketing" },
      { valor: "Producción" },
      { valor: "Finanzas" },
      { valor: "Logística" },
      { valor: "Atención al Cliente" },
      { valor: "Tecnologías de la Información" },
      { valor: "Investigación y Desarrollo" },
      { valor: "Otros (especificar)" },
    ],
  },
  {
    pregunta: "2. Puesto que ocupa actualmente:  ",
    preguntaInputName: "socioeconomico2",
    opciones: [
      { valor: "Gerente" },
      { valor: "Supervisor" },
      { valor: "Analista" },
      { valor: "Coordinador" },
      { valor: "Ejecutivo" },
      { valor: "Asistente" },
      { valor: "Técnico" },
      { valor: "Operador" },
      { valor: "Administrativo" },
      { valor: "Otros (especificar)" },
    ],
  },
  {
    pregunta: "3. Cuánto tiempo lleva en la empresa:  ",
    preguntaInputName: "socioeconomico3",
    opciones: [
      { valor: "Menos de 6 meses" },
      { valor: "6 meses a 1 año" },
      { valor: "1 a 3 años" },
      { valor: "3 a 5 años" },
      { valor: "5 años" },
      { valor: "6 a 10 años" },
      { valor: "11 a 20 años" },
      { valor: "mas de 20 años" },
    ],
  },
  {
    pregunta: "4. Es trabajador de: confianza ó :  ",
    preguntaInputName: "socioeconomico4",
    opciones: [{ valor: "confianza" }, { valor: "sindicalizado" }],
  },
];